<a href="https://colab.research.google.com/github/prince2004coder/Data-Science-/blob/main/numpyQ(lec3).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np




In [13]:

matrix = np.random.randint(1, 91, (5, 5))

print(matrix)

column_mean =  np.mean(matrix, axis=0)
print("Column-wise Mean:",  column_mean)


row_mean  = np.mean(matrix, axis=1)
print("Row-wise Mean:",  row_mean)


matrix2 = np.where(matrix % 2 == 0, -1, matrix)
print(matrix2)

row_sorted = np.sort(matrix, axis=1)
print(row_sorted)


column_sorted = np.sort(matrix, axis=0)
print(column_sorted)



row_sum = np.sum(matrix, axis=1)
print(" Row wise sum:" ,row_sum)


column_sum = np.sum(matrix, axis=0)
print("Column wise sum:", column_sum)


count_column = np.sum(np.where(matrix2 < 0, 1, 0) , axis=0)
print("count colummn:", count_column)



[[61 50  4 46  4]
 [30 45 23 76  4]
 [37 18 32 60 48]
 [76 76  6 21  5]
 [11 35 73 62 89]]
Column-wise Mean: [43.  44.8 27.6 53.  30. ]
Row-wise Mean: [33.  35.6 39.  36.8 54. ]
[[61 -1 -1 -1 -1]
 [-1 45 23 -1 -1]
 [37 -1 -1 -1 -1]
 [-1 -1 -1 21  5]
 [11 35 73 -1 89]]
[[ 4  4 46 50 61]
 [ 4 23 30 45 76]
 [18 32 37 48 60]
 [ 5  6 21 76 76]
 [11 35 62 73 89]]
[[11 18  4 21  4]
 [30 35  6 46  4]
 [37 45 23 60  5]
 [61 50 32 62 48]
 [76 76 73 76 89]]
 Row wise sum: [165 178 195 184 270]
Column wise sum: [215 224 138 265 150]
count colummn: [2 3 3 4 3]


In [16]:
#question 2
#inventory control system

#tasks

stock = np.random.randint(20,80,(5,5))
print(stock)
demand = np.random.randint(20,80,(5,5))
print(demand)

remaning_stock = stock - demand
print(remaning_stock)

remaning_stock = np.where(remaning_stock < 0, 0, remaning_stock)
print(remaning_stock)


# find total shortage,,,,products with zero stock ,,,, sort each row based on remaining stock

total_shortage = np.sum(np.where(remaning_stock<0, remaning_stock*-1, 0))

print(total_shortage)


product_shortage = np.sum(np.where(remaning_stock<0, 1, 0), axis=0)
print(product_shortage)



sorted = np.sort(remaning_stock, axis=1)
print(sorted)


[[65 56 20 22 64]
 [48 29 64 47 32]
 [22 21 78 78 21]
 [20 41 30 67 44]
 [50 76 33 70 44]]
[[56 68 64 70 44]
 [31 59 41 37 57]
 [46 48 65 26 62]
 [39 70 32 40 78]
 [47 60 74 31 49]]
[[  5  -5 -33  10  -1]
 [ 14  14  50  33 -37]
 [-10 -32   3  23   0]
 [-16 -10   3   5   8]
 [ 24  31  56  -6 -28]]


In [18]:
import pandas as pd

file_ = pd.read_csv('student_data(DS).csv')
print(file_)






      study_hours  attendance  sleep_hours  internet_usage  \
0               7          56            8               7   
1               4          69            5               3   
2              11          60            7               6   
3               8          99            9               8   
4               5          52            8               6   
...           ...         ...          ...             ...   
9995            2          58            9               7   
9996            7          98            6               9   
9997           10          44            8               5   
9998           10          75            7               5   
9999            2          70            6              11   

      assignments_completed  previous_score  exam_score placement_status  
0                        10              62      100.00           Placed  
1                         8              56      100.00           Placed  
2                        10   